name: Update the DeTT&CT data source to techniques mapping
on:
  push:
    branches: [ master ]
    paths:
      - 'data/dettect_data_sources.xlsx'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/workflows/scripts/requirements_update_dettect_data_sources.txt

      - name: Update the DeTT&CT data source to techniques mapping
        working-directory: ./.github/workflows/scripts
        run: |
          python update_dettect_data_sources.py

      - name: Check for changes
        id: changes
        run: |
          OUTPUT=`git status`
          echo ::set-output name=GIT_STATUS::${OUTPUT}
          echo $OUTPUT

      - name: Commit files (if applicable)
        if: contains(steps.changes.outputs.GIT_STATUS, 'modified')
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update the DeTT&CT data source to techniques mapping"

      - name: Push changes (if applicable)
        if: contains(steps.changes.outputs.GIT_STATUS, 'modified')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}

